google/fhir-data-pipes

- batch/pom.xml
- common/pom.xml
- common/src/main/java/org/openmrs/analytics/BaseArgs.java
- common/src/main/java/org/openmrs/analytics/ParquetUtil.java
- common/src/test/java/org/openmrs/analytics/ParquetUtilTest.java
- pom.xml
- streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java
- streaming-binlog/src/main/java/org/openmrs/analytics/FhirConverter.java
- streaming-binlog/src/test/java/org/openmrs/analytics/FhirConverterTest.java
Note the time based policy create new files simulating the idea of windowing in Beam. The row-group-size based policy
just flushes the content as a row-group which has size and performance implications but no new file is generated.
Partially fixes #65 
TESTED:
Ran the following for a set of events with a few thousand Observations and checked that during the time pipeline was running:
- The Observation Parquet files were being flushed because of the row-group-size limit.
- New files were created every 2 minutes (because of `--secondsToFlushParquetFiles=120`).
```
$ mvn exec:java -pl streaming-binlog "-Dexec.args=--databaseHostName=localhost \
--databasePort=3306 --databaseUser=[DBUSER] --databasePassword=[DBPASS] \
--databaseSchema=no-atomfeed-p9021-v11S --databaseServerId=77 …
```
> Added time constraints for Parquet file generation and row-group-size flush policy.

- README.md
- batch/Dockerfile
- batch/src/main/java/org/openmrs/analytics/FhirEtl.java
- common/src/main/java/org/openmrs/analytics/BaseArgs.java
- common/src/main/java/org/openmrs/analytics/FhirStoreUtil.java
- docker-compose.yaml
- streaming-atomfeed/Dockerfile
- streaming-atomfeed/src/main/java/org/openmrs/analytics/FhirStreaming.java
- streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java
- streaming-binlog/src/main/java/org/openmrs/analytics/FhirConverter.java
- streaming-binlog/src/test/java/org/openmrs/analytics/FhirConverterTest.java
- Add support for having both FHIR store and Parquet output enabled at the same time  . This is controlled by passing the` --fhirSinkPath`  and '--fileParquetPath' arguments or leaving them out 
-  I also corrected the parameter naming to have uniform argument names throughout the three sub-modules
TESTED:
```
--databasePort=3308 --databaseUser=root --databasePassword=Admin123\
--databaseName=mysql --databaseSchema=openmrs --databaseServerId=223344 \
--openmrsServerUrl=http://localhost:8081/openmrs \
--fhirSinkPath=http://localhost:8888/fhir \
--sinkUserName=hapi --sinkPassword=hapi123 \
--fileParquetPath=/tmp/" 
```
```
mvn compile  exec:java -pl …
```
> Add support for having both FHIR store and Parquet output enabled at the same time

- batch/src/main/java/org/openmrs/analytics/FhirEtl.java
Fixes #94 
TESTED:
Ran
```
java -cp batch/target/fhir-batch-etl-bundled-0.1.0-SNAPSHOT.jar org.openmrs.analytics.FhirEtl --openmrsServerUrl=http://localhost:8099/openmrs --fileParquetPath=tmp/TEST_docker_batch/ --searchList=Patient
```
then verified that the number of patients is 1000 which is the same in the test data set:
```
java -jar ~/git_repos/read_only/parquet-mr/parquet-tools/target/parquet-tools-1.12.0-SNAPSHOT.jar rowcount tmp/TEST_docker_batch/Patient/
```
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and …
> changed the default of batchSize flag

- README.md
- streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java
- streaming-binlog/src/main/java/org/openmrs/analytics/model/EventConfiguration.java
- streaming-binlog/src/main/java/org/openmrs/analytics/model/GeneralConfiguration.java
- streaming-binlog/src/test/java/org/openmrs/analytics/DebeziumListenerTest.java
- utils/dbz_event_to_fhir_config.json
Issue #51
moved the the debezium settings to `dbz_event_to_fhir_config.json` config file
and also moved the debezium settings to the event configuration class so that we have all the configs together 
e2e test
TESTED:
--databaseUser=root --databasePassword=debezium \
--databaseSchema=openmrs \
--openmrsServerUrl=http://localhost:8099/openmrs \
--openmrsfhirBaseEndpoint=/ws/fhir2/R4 \
--snapshotMode=schema_only \
--fhirSinkPath=http://localhost:8098/fhir \
--sinkUserName= --sinkPassword= "
---
This change is [<img src="https://reviewable.io/review_button.svg" height="34" align="absmiddle" alt="Reviewable"/>](https://reviewable.io/reviews/googlecloudpl …
> Move:move debezium specific settings to a json file

- utils/create_fhir_store.sh
Because we switched back to R4 as the default in the ETL pipelines too.
This is a minor change which is basically reverting back to a version which was tested before.
> Revert back to R4

- streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java
switching the jdbcUrl port from 3308 to 3306 to enable binlog pipeline to run and fetch uuids from parent tables for tables without uuid columns
> clean-up:changing jdbcUrl port

- batch/src/main/java/org/openmrs/analytics/FhirEtl.java
- batch/src/main/java/org/openmrs/analytics/FhirEtlOptions.java
This is to address the incremental Parquet file generation requirements which might be related to Issue #136. With the added `--secondsToFlushFiles` option we can force Beam to generate Parquet files in multiple batches (note this is different from setting `rowGroupSize` which is done differently).
TESTED:
Ran:
```
$ java -cp batch/target/fhir-batch-etl-bundled-0.1.0-SNAPSHOT.jar org.openmrs.analytics.FhirEtl \
--openmrsServerUrl=http://localhost:8099/openmrs --jdbcUrl=jdbc:mysql://localhost:3306/openmrs \
--searchList=Patient,Encounter,Observation --jdbcFetchSize=1000  --jdbcMaxPoolSize=100 --jdbcModeEnabled \
--targetParallelism=10 --numFileShards=3 --secondsToFlushFiles=180 --outputParquetPath=[PATH]
```
and verified that the files are generated in 3 minutes intervals.
I also tried a …
> Added an option to flush output files in chunks

- batch/src/main/java/org/openmrs/analytics/FhirSearchUtil.java
- batch/src/test/java/org/openmrs/analytics/FhirSearchUtilTest.java
This adds an extra null-check in `getNextUrl`. Although it is not clear how this condition can be triggered but some test runs against real data have shown this behavior, so better to prevent crashing the pipeline.
TESTED:
Sample run:
```
java -cp batch/target/fhir-batch-etl-bundled-0.1.0-SNAPSHOT.jar org.openmrs.analytics.FhirEtl \
--openmrsServerUrl=http://localhost:8099/openmrs --resourceList=Encounter,Observation \
--targetParallelism=10 --numFileShards=3 --secondsToFlushFiles=1200 \
--outputParquetPath=[PATH] --jdbcUrl=jdbc:mysql://localhost:3306/openmrs \
--jdbcMaxPoolSize=100 --jdbcModeEnabled --activePeriod=2020-11-09T10:00:00_2020-11-11
```
No? Unsure? -> [configure your IDE](https://wiki.openmrs.org/display/docs/How-To+Setup+And+Use+Your+IDE), format the code and add the changes …
> Added a null check in getNextUrl

- bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java
- pipelines/common/src/main/java/org/openmrs/analytics/ParquetUtil.java
- pipelines/common/src/test/java/org/openmrs/analytics/ParquetUtilTest.java
- pipelines/common/src/test/resources/observation_decimal_bundle.json
This fixes #156. This was already applied to Bunsen and verified that fixes the issue on real data too ([here](https://github.com/GoogleCloudPlatform/openmrs-fhir-analytics/issues/156#issuecomment-887599927)). We were just waiting for the Bunsen to be forked here to directly apply this change.
TESTED:
See [here](https://github.com/GoogleCloudPlatform/openmrs-fhir-analytics/issues/156#issuecomment-887599927).
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and [Python](https://google.github.io/styleguide/pyguide.html) style guides. Note, when in conflict, OpenMRS …
> Fixes the ArrayTypeException in the Bunsen code.

- synthea-hiv/generator/Dockerfile
Reverts GoogleCloudPlatform/openmrs-fhir-analytics#242
as `https://github.com/synthetichealth/synthea/releases/download/master-branch-latest/synthea-with-dependencies.jar`
no longer contains any vulnerability as [this](https://github.com/synthetichealth/synthea/pull/969) PR in Synthea got merged
> Revert "Delete Dockerfile as it downloads Synthea JAR that uses Log4j < 2.16.0"

- docker/config/application.yaml
- docker/config/hapi-postgres-config_local.json
- docker/config/thriftserver-hive-config_local.json
- docker/hapi-compose.yml
Add auto-table generation to single-machine docker compose config.
Also adjusts network settings to allow single-machine docker compose to connect to the test hapi-fhir server using default values. This leverages the fact that docker-compose creates a default network based on the folder the config file is in (in this case, the network is `docker_default`) and connects all containers to it. A side effect is that if you have multiple docker-compose configs in the same directory, they have the same default network name and will connect to it. Because of that, you can reference services by hostname and the container's port number.
After the changes hapi-fhir-server still connects to an external network named `cloudbuild`, but I was not sure how/what to test to make sure the tests that …
> Add auto-table generation to single-machine docker compose config.

- pipelines/controller/src/main/java/org/openmrs/analytics/HiveTableManager.java
- pipelines/controller/src/main/java/org/openmrs/analytics/PipelineManager.java
- Added fix for auto creation of resources upon incremental run. The output directory was not being set properly.
- Also added mechanism to create canonical table on each run. Be it full or incremental, the pipeline shall drop existing canonical tables if any and create new based on newly generated parquet files: https://github.com/google/fhir-data-pipes/issues/530
- I tested build locally and made sure nothing is breaking.
- I tested full batch run and verified that resources are being created.
- I tested incremental run and verified that resources are being created.
TESTED:
Tested locally for batch and incremental runs.
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and [Python](https://google.github.io/styleguide/pyguide.html) style …
> Fix for auto resource creation on incremental run

- bunsen/bunsen-core-r4/src/main/java/com/cerner/bunsen/definitions/r4/R4StructureDefinitions.java
- bunsen/bunsen-core-stu3/src/main/java/com/cerner/bunsen/definitions/stu3/Stu3StructureDefinitions.java
Fixes #556 
The root cause of the failure for Immunization was the `doseNumber[x]` field of `protocolApplied` in Immunization(https://hl7.org/fhir/immunization.html). And the reason that failed was because of `positiveInt` primitive datatype. In the code that is fixed now, we were using `toLowerCase()` when comparing the types which was failing for `positiveInt`. This does not seem to be a new regression and/or caused by R4 migration. It has been in Bunsen code since a long time ago and even in STU3 we have `positiveInt` (and it is suspicious why it was not discovered before).
TESTED:
I ran this command before and after this fix:
```
java -cp ./pipelines/batch/target/batch-bundled-0.1.0-SNAPSHOT.jar \
org.openmrs.analytics.FhirEtl --fhirServerUrl=http://localhost:9001/fhir \ …
```
> Fixes incorrect primitive type comparison in Bunsen

- docker/compose-controller-spark-sql.yaml
The issue we reported with the 3.3 version of the Bitnami Spark image is now fixed ([here](https://github.com/bitnami/containers/issues/19802#issuecomment-1381498714)); hence reverting to that version.
TESTED:
Ran the HAPI server using `hapi-compose.yml` and the modified compose file `compose-controller-spark-sql.yaml` then ran a full-run of the pipeline and queried the created DWH.
> Revert spark image version back to 3.3

- pipelines/batch/pom.xml
Due to the recent upgrades made there is an regression issue introduced to the workflow of 'persisting the parquet files to the GCS file system'. This PR contains the change to upgrade the necessary jar so that this workflow runs correctly. 
TESTED:
Batch runs and incremental runs were made and checked for the successful creation of the parquet files in the GCS file system.
> Upgrade mysql driver jar to fix the regression issue

- pipelines/batch/src/main/java/org/openmrs/analytics/ResourceTag.java
- pipelines/batch/src/test/java/org/openmrs/analytics/ResourceTagTest.java
ResourceTag was not getting serialised appropriately as it has a member Coding which does not implement equals method which in turn throws warning while running the pipeline. Added equals override method to ResourceTag method which takes care of Coding equals and other properties as well.
Fixes https://github.com/google/fhir-data-pipes/issues/646
Tested.
TESTED:
Tested on local and made sure pipeline is exporting output with DirectRunner without any warnings.
Also, tested with unit test case.
No? Unsure? -> execute command `git pull …
> Added equals method to ResourceTag to avoid Beam mutation warning

- docker/config/application.yaml
- pipelines/batch/src/main/java/org/openmrs/analytics/EtlUtils.java
- pipelines/common/src/main/java/org/openmrs/analytics/DwhFiles.java
- pipelines/common/src/test/java/org/openmrs/analytics/GcsDwhFilesTest.java
- pipelines/common/src/test/java/org/openmrs/analytics/LocalDwhFilesTest.java
- pipelines/controller/config/application.yaml
- pipelines/controller/src/main/java/org/openmrs/analytics/DWHFilesManager.java
- pipelines/controller/src/main/java/org/openmrs/analytics/DataProperties.java
- pipelines/controller/src/main/java/org/openmrs/analytics/DwhFilesManager.java
- pipelines/controller/src/main/java/org/openmrs/analytics/PipelineManager.java
- pipelines/controller/src/main/resources/application.yaml
- pipelines/controller/src/test/java/org/openmrs/analytics/GcsDwhFilesManagerTest.java
- pipelines/controller/src/test/java/org/openmrs/analytics/LocalDwhFilesManagerTest.java
- pipelines/controller/src/test/resources/application-test.properties
The following changes have been made 
- Implemented a periodic purge scheduler
- The purge job will scan for the DWH snapshots and retain only the last N successfully completed snapshots. The previously completed DWH snapshots will be deleted. Snapshots which are incomplete will be ignored by this job i.e. they wont be considered for deletion.
- For successful state of a DWH snapshot we now create two timestamp files (1) timestamp_start.txt at the beginning of the pipeline run (2) timestamp_end.txt at the end of the pipeline run, as opposed to only one file (timestamp.txt) which we used to create earlier.
- On start of the application we now initialise to the most recent successfully completed snapshot (which checks for the presence of both the timestamp files).
The changes have been …
> Implemented a purge policy for Old DWH snapshots

- bunsen/pom.xml
- cloudbuild.yaml
- pipelines/pom.xml
Added jococo plugin to create local coverage report.
Added a step in cloudbuild which will publish the created report to codecove.io.
When each pull request is created, upon run of cloudbuild step, when the report gets uploaded to codecov.io, developers can view the report on their website like this: https://app.codecov.io/gh/google/fhir-data-pipes/tree/codecov
It shows coverage on bunsen and pipeline modules. Clicking deep into folders, they can see coverage line-byline as well.
Codecov also generated report to be displayed in github as its been shown in this pull request.
Codecov needs a token for uploading coverage reports. I have added this token in cloud build as Substitution variable. And I am using that substitution variable in cloudbuild.
Fixes …
> Integrate codecov with cloudbuild to publish coverage report

- docker/compose-controller-spark-sql.yaml
- pipelines/controller/src/main/java/org/openmrs/analytics/PipelineManager.java
Upon pipeline restart, application scans snapshots directories and creates tables per resource. With incremental run, there is a folder created incremental_run which should be skipped by the application while doing this scan. Added the fix.
Fixes https://github.com/google/fhir-data-pipes/issues/689
Tested.
TESTED:
Verified that pipeline controller starts up without any issues. Earlier this was not coming up because it used to fail with exception saying that encountered text files instead of parquet files.
No? Unsure? -> execute command …
> Fixed bug in auto resource tables creation upon pipeline restart

- docker/compose-controller-spark-sql.yaml
- e2e-tests/controller-spark/controller_spark_sql_validation.sh
Cloud build fails intermittently on dockerised pipeline's incremental run stage. Upon investigation, I found that the thread remains active after full run and when the controller receives request for incremental run, it throws error saying that A pipeline is still running. This can be because it is trying to create resource tables.
Introducing delay between the runs to see if this solves the problem.
Tested
TESTED:
N/A
> Added sleep to introduce delay between full and incremental runs.

- cloudbuild.yaml
- docker/compose-controller-spark-sql-single.yaml
- docker/config/application.yaml
- e2e-tests/controller-spark/controller_spark_sql_validation.sh
When I run docker compose using compose-controller-spark-sql.yaml then thriftserver intermittently fails to connect to spark master which results in cloud build failure sometimes.
Switched to compose-controller-spark-sql-single.yaml where there are no spark master and worker containers.
Fixes #708 
Tested
TESTED:
Tested on my local that containers are coming up correctly.
> Switched to alternate docker compose to fix build flakiness

- docker/compose-controller-spark-sql-single.yaml
- docker/compose-controller-spark-sql.yaml
Thriftserver healthcheck's test was opening hive database connection every "interval" seconds and was populating exception logs.
Changed the test condition to just "beeline help" .
Fixes https://github.com/google/fhir-data-pipes/issues/714
Tested
TESTED:
Verified that both the docker compose are bringing containers up properly. Verified multiple times to make sure there is no intermittent behaviour.
> Updated thiriftserver healthcheck test condition in docker compose files

- docker/compose-controller-spark-sql-single.yaml
This is to fix #728.
TESTED:
Manually ran `compose-controller-spark-sql-single.yaml` and tested the TX_NEW query on the 800K patient + 160M observation dataset and it succeeded.
> Increased Spark driver memory in the single process mode

- docker/config/flink-conf.yaml
- pipelines/controller/config/flink-conf.yaml
Fixed the flink job listener which tracks the pipeline metrics for docker
TESTED:
Started the docker compose `compose-controller-spark-sql-single.yaml` and tested for the Batch run to see if the metrics are collected properly.
> Fixed the flink job listener which tracks the pipeline metrics for docker

- bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java
- bunsen/bunsen-core-r4/src/main/java/com/cerner/bunsen/definitions/r4/R4StructureDefinitions.java
- bunsen/bunsen-core-stu3/src/main/java/com/cerner/bunsen/definitions/stu3/Stu3StructureDefinitions.java
- bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/DefinitionVisitorsUtil.java
- bunsen/pom.xml
- cloudbuild.yaml
- docker/config/flink-conf.yaml
- utils/flink-conf.yaml
This fixes #758 by adding the full path of fields (using the traversal stack) to record names. This way we can differentiate between `QuestionnaireResponse.item.answer.item.answer.item` and `QuestionnaireResponse.item.answer.item` which is needed to properly apply recursion limits.
This PR has two commits; the first one is a simpler solution that I originally had but only partially solves the problem. I have kept it for record keeping and future reference.
This also comments out the `codecov` part of `cloudbuild.yaml` as it has started to fail for some reason.
TESTED:
Ran the pipeline against the QuestionnaireResponse that had problem before and confirmed that answers are generated in the Parquet file if the recursion depth is large enough (tried with max-depth 3). I have not changed the …
> Fixes missing QuestionnaireResponse `answer` fields

- pipelines/batch/src/main/java/org/openmrs/analytics/ConvertResourceFn.java
- pipelines/batch/src/main/java/org/openmrs/analytics/MetricsConstants.java
Handling large resource parsing exception using DataFormatException
I have used try/catch block to catch the DataFormatException while parsing JSON encoded FHIR content.
Issue : https://github.com/google/fhir-data-pipes/issues/755
TESTED:
After adding the try/catch block, I ran the Pipeline and it generated the Parquet files.
> Handling large resource parsing exception using DataFormatException

- bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java
- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/R4AvroConverterTest.java
- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/Stu3AvroConverterTest.java
- bunsen/bunsen-core-r4/src/main/java/com/cerner/bunsen/definitions/r4/R4StructureDefinitions.java
- bunsen/bunsen-core-stu3/src/main/java/com/cerner/bunsen/definitions/stu3/Stu3StructureDefinitions.java
- bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/HapiCompositeConverter.java
- pipelines/batch/src/main/java/org/openmrs/analytics/ConvertResourceFn.java
- pipelines/batch/src/test/java/org/openmrs/analytics/JdbcFetchHapiTest.java
This fixes some of the issues mentioned in #757. It also adds a path example where the recursion depth limit is disabled. The example is commented out until we decide we really want to support this pattern. If we do, then those exceptional paths should be exposed as configuration parameters.
TESTED:
Ran the pipeline with a sample QuestionnaireResponse that had deep `item.item.item...` recursions and confirmed that all of the `answer` fields are transformed into the Parquet file without increasing the general recursion max-depth, if that path is provided as an exception.
Also tested the same scenario by increasing max-depth and no exceptional paths; at levels 1, 2, 3, etc. the expected fields were present. …
> Fixed bugs in recursion depth and added a path example

- pipelines/batch/src/main/java/org/openmrs/analytics/ConvertResourceFn.java
- pipelines/batch/src/main/java/org/openmrs/analytics/HapiRowDescriptor.java
- pipelines/batch/src/main/java/org/openmrs/analytics/JdbcFetchHapi.java
- pipelines/batch/src/test/java/org/openmrs/analytics/ConvertResourceFnTest.java
- Modified query in the `JdbcFetchHapi.java` to get the forcedId from the database.
- Used forced-id in the `HapiRowDescriptor`
- Used forcedId to as a resource id in `writeResource()` function in the `ConvertResourceFn`
**Issue**:
#752 
TESTED:
Ran the following command to transform the FHIR resources.
`java -cp ./pipelines/batch/target/batch-bundled-0.1.0-SNAPSHOT.jar org.openmrs.analytics.FhirEtl --fhirServerUrl=[FHIR-SERVER-RUL] --outputParquetPath=./docker/dwh/ --resourceList=Patient,Encounter,Observation  --fhirDatabaseConfigPath=./utils/hapi-postgres-config.json --jdbcModeEnabled=true --jdbcModeHapi=true --jdbcMaxPoolSize=50 --jdbcFetchSize=1000`
Verified that the id of the original FHIR resource match the resource id in transformed paquet file. …
> Fix resource ID's mismatch between original FHIR resource and the corresponding resource in the parquet file in HAPI JDBC mode.

- pipelines/controller/src/main/java/com/google/fhir/analytics/DataProperties.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/DataPropertiesTest.java
- pipelines/controller/src/test/resources/application-test.properties
Added user name and password to the controller configuration for better FHIR search support. Fixes #677.
TESTED:
Added the `fhirServerPassword` and `fhirServerUserName` properties to the controller `application.yaml` and ensured the properties were set and fetching to a FHIR server worked.
> Add user name and password to controller config

- docker/config/flink-conf.yaml
Temporarily reducing the Flink memory params to work fine in low resource settings.
TESTED:
Tested the full run on the application deployed via docker 
> Temporarily reducing the Flink memory params for low resource machines

- bunsen/pom.xml
- pipelines/pom.xml
Fixes #725 (recreation of #788)
The root cause of the dependency issues seems to be diamond dependencies on Jackson through different libraries. The problem is that the latest release of Beam depends on `2.14.1` of `jackson-core` and that causes `NoClassDefFound` exceptions due to other libraries (e.g., Hapi 6.6.2) depending on newer Jackson.
TESTED:
Relying on unit/e2e tests.
> Fixes issues for upgrading to newer hapi.fhir libs (recreation of #788)

- docker-entrypoint.sh
- docker/config/flink-conf.yaml
Reduced the JVM heap and Flink memory configurations to support low resource environments.
Tested the Qwiklabs codelab setup prepared for the OHS analytics demo.
> Reducing the memory configuration values to support low resource env

- pipelines/controller/config/application.yaml
Disabled the Thrift Hive Server in Development mode
NA
TESTED:
NA
> Disable the Thrift Hive Server in Development mode

- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/R4AvroConverterTest.java
- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/Stu3AvroConverterTest.java
- pipelines/common/src/main/java/com/google/fhir/analytics/DwhFiles.java
- pipelines/common/src/main/java/com/google/fhir/analytics/ParquetUtil.java
- pipelines/common/src/test/java/com/google/fhir/analytics/GcsDwhFilesTest.java
- pipelines/common/src/test/java/com/google/fhir/analytics/LocalDwhFilesTest.java
- pipelines/common/src/test/java/com/google/fhir/analytics/ParquetUtilTest.java
- pipelines/controller/config/application.yaml
- pipelines/controller/src/main/java/com/google/fhir/analytics/DwhFilesManager.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/LocalDwhFilesManagerTest.java
- pipelines/controller/src/test/resources/application-test.properties
Fixes #843 
In Windows platform usage of [ResourceId.resolve(..)](https://github.com/apache/beam/blob/6a2db44c41051e7ceee03225021bfeb4e0c2442f/sdks/java/core/src/main/java/org/apache/beam/sdk/io/fs/ResourceId.java#L85) method to resolve paths with glob expressions (containing multiple special characters like `**`, `*/*` etc) is leading to the error `java.nio.file.InvalidPathException: Illegal char <:> at index 2: /C:/...`. This is because it internally uses `Paths.get()` which fails in Windows OS platform to resolve the paths correctly. Refer https://bugs.openjdk.org/browse/JDK-8197918 for details. Also, the documentation of this api [ResourceId.resolve(..)](https://github.com/apache/beam/blob/6a2db44c41051e7ceee03225021bfeb4e0c2442f/sdks/java/core/src/main/java/org/apache/beam/sdk/io/fs/R …
> Changes to support the Windows OS platform

- Dockerfile
- docker-entrypoint.sh
- docker/.env
- docker/compose-controller-spark-sql-released.yaml
- docker/compose-controller-spark-sql-single.yaml
- docker/compose-controller-spark-sql.yaml
- docker/config/application.yaml
- e2e-tests/Dockerfile
- pipelines/batch/src/main/java/com/google/fhir/analytics/ParquetMerger.java
- pipelines/controller/config/application.yaml
- pipelines/controller/pom.xml
- pipelines/controller/src/main/java/com/google/fhir/analytics/DataProperties.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/FlinkConfiguration.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/FlinkConfigurationTest.java
- pipelines/pom.xml
- pipelines/streaming/Dockerfile
Fixes #823 
- Enabled a feature flag to automate the generation of `flink-conf.yaml` based on the `numThreads` in `application.yaml` file and the number of `cores` available in the machine.
- If the flag is disabled, then the `flink-conf.yaml` directed by the env. var `FLINK_CONF_DIR` will be used. If var is empty, then default conf will be used.
- JAVA_OPTS can be set to override the default JVM heap and other parameter values.
-  The application will fail to launch if the JVM Off Heap memory is insufficient for the Flink cluster to launch.
- Fixes the regression introduced by this [change](https://github.com/google/fhir-data-pipes/pull/670) where the maxWorkers was defaulted to 1 and in turn the num of shards for parquet files was also 1.
Tested `Full Run` and `Incremental Run` by …
> Generate `flink-conf.yaml` file automatically to set optimum conf values

- docker/config/views/observation_flat_view.json
- docker/config/views/patient_flat_view.json
- pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcResourceWriter.java
- pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewApplicator.java
- pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewDefinition.java
- pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewSchema.java
- pipelines/common/src/test/java/com/google/fhir/analytics/view/ViewApplicatorTest.java
- pipelines/common/src/test/java/com/google/fhir/analytics/view/ViewDefinitionTest.java
Adds an index on the `id` columns (and makes that column mandatory) and deletes record with the same resource IDs before adding them to the DB. This is required for #916 to be able to update old view rows.
TESTED:
Ran the pipeline for both small and large datasets (~16M observations). The impact of the index/deletion on performance seems to be ~3% or less (depending on various scenarios tested).
> added an ID index and delete old view rows

- docker-entrypoint.sh
- docker/.env
- docker/config/application.yaml
- pipelines/batch/src/main/java/com/google/fhir/analytics/BasePipelineOptions.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/FhirEtlOptions.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcFetchHapi.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/ParquetMerger.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/ParquetMergerOptions.java
- pipelines/controller/config/application.yaml
- pipelines/controller/src/main/java/com/google/fhir/analytics/DataProperties.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/FlinkConfiguration.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/FlinkConfigurationTest.java
Fixes #900
The incremental run used to fail when there were high number of FHIR resources to be processed already present in the system. This was because during the incremental run, the delta records had to be merged with the existing records in the parquet files and this needed reading of all the parquet records.
It turned out to be that the minimum amount of memory needed to read from all the parquet shards in parallel is determined by the below formula
```memoryNeeded = Misc memory for JVM stack + (#Parallel Pipeline Threads * #Parallel Pipelines * Parquet Row Group Size)```
This was causing failures for the default parquet row size of 128mb which needed a high memory to load these records into in-memory by all the pipeline threads.
Changes are made to reduce the Parquet Row Group Size …
> Fix for the high memory usage

- docker/hapi-compose.yml
- pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcFetchHapi.java
This is a follow-up to #926, please see [this comment](https://github.com/google/fhir-data-pipes/pull/926#issuecomment-1936912782) for details.
Note the changes in the SQL query are cosmetic, to be more readable.
TESTED:
Relying on e2e tests (tested this with different versions of HAPI JPA).
> Updates the HAPI JPA version in e2e to latest

- docker/config/application.yaml
- pipelines/batch/src/main/java/com/google/fhir/analytics/ParquetMerger.java
- pipelines/controller/config/application.yaml
- pipelines/controller/src/main/java/com/google/fhir/analytics/DataProperties.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/FlinkConfiguration.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
Fixes #948 
Deprecated the `maxWorkers` param which was used to set the `maxParallelism` param in `FlinkPipelineOptions`. This param only gets used in a Streaming environment, since the pipelines doesn't use any streaming currently this parameter is not used and hence deprecated.
This PR also contains changes which were missed in the PR #935.
Relined on e2e.
Also, locally verified the `Parquet Row Group Sizes` for the newly created files.
TESTED:
No? Unsure? -> [configure your …
> Deprecation of `maxWorkers` param

- docker/hapi-compose.yml
HAPI has released a latest [docker image](https://hub.docker.com/layers/hapiproject/hapi/latest/images/sha256-c3df28c706f1d7565df595ef9aef75ce65e744f19be6b5acc00c5610c9635657?context=explore) on 27-Feb-2023. In this version due to some upgrades on the `hibernate` dependencies, the earlier [hibernate dialect ](https://github.com/google/fhir-data-pipes/blob/2fe486e36aecf77194b5f7df9d7dfdde48cf487d/docker/hapi-compose.yml#L42) setting `spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQL95Dialect` is not working anymore. It results in the below error. 
Error logs on start of HAPI server
--------------------------------
```
hapi-server    | Caused by: org.hibernate.boot.registry.selector.spi.StrategySelectionException: Unable to resolve name …
```
> Update Hibernate.dialect for latest HAPI version

- pipelines/batch/pom.xml
- pipelines/common/pom.xml
- pipelines/controller/pom.xml
- pipelines/pom.xml
- pom.xml
This was an attempt to fix #939 but unfortunately it does not change the uber jar sizes much; but it fixes some warning messages during build. Some of the bigger dependencies that might be worth shrinking like `beam-sdks-java-io-google-cloud-platform` (over 100 MB) needs more testing that are not covered by our e2e, so I left them intact.
TESTED:
> Some minor pom clean-ups

- bunsen/pom.xml
- pipelines/pom.xml
This fixes the build failure issues for the PRs #957 and #895 
Relied on e2e test cases
TESTED:
> Fix for logback version upgrade

- .github/workflows/codecov.yml
- Dockerfile
- cloudbuild.yaml
- coverage/pom.xml
- pipelines/pom.xml
- pom.xml
Attempting to address issue #666.
TESTED:
Ran `mvn` locally and verified that the Jacoco report generated locally makes sense.
> added codecov GH action

- bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java
- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/R4AvroConverterUsCoreTest.java
- bunsen/bunsen-avro/src/test/resources/r4-custom-schemas/bunsen-test-patient-schema.json
- bunsen/bunsen-avro/src/test/resources/r4-us-core-schemas/us-core-condition-schema.json
- bunsen/bunsen-avro/src/test/resources/r4-us-core-schemas/us-core-observation-schema.json
- bunsen/bunsen-avro/src/test/resources/r4-us-core-schemas/us-core-patient-schema.json
- bunsen/bunsen-avro/src/test/resources/stu3-custom-schemas/bunsen-test-patient-schema.json
- bunsen/bunsen-avro/src/test/resources/stu3-us-core-schemas/us-core-observation-schema.json
- bunsen/bunsen-avro/src/test/resources/stu3-us-core-schemas/us-core-patient-schema.json
- bunsen/bunsen-core-r4/src/main/java/com/cerner/bunsen/definitions/r4/R4StructureDefinitions.java
- bunsen/bunsen-core-r4/src/test/java/com/cerner/bunsen/r4/TestData.java
- bunsen/bunsen-core-stu3/src/main/java/com/cerner/bunsen/definitions/stu3/Stu3StructureDefinitions.java
- bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/HapiConverter.java
- bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/StructureDefinitions.java
- bunsen/extension-structure-definitions/src/main/java/com/cerner/bunsen/common/R4UsCoreProfileData.java
- bunsen/extension-structure-definitions/src/main/resources/r4-us-core-definitions/StructureDefinition-sdc-questionnaire-itemAnswerMedia.json
- bunsen/extension-structure-definitions/src/main/resources/r4-us-core-definitions/StructureDefinition-sdc-questionnaire-itemMedia.json
- e2e-tests/controller-spark/controller_spark_sql_validation.sh
- e2e-tests/pipeline_validation.sh
- pipelines/common/src/test/java/com/google/fhir/analytics/ParquetUtilTest.java
- pipelines/common/src/test/resources/questionnaire_response.json
Fixes #1027 
The below mentioned changes have been made as part of this PR
- Handled the error properly when the StructureDefinitions for extensions are missing.
- The DoubleConverter for decimal data types has been fixed, which was failing for Leaf Extensions containing `Decimal` data types.
- The avro schema name for the `Reference` types have been changed to contain a full path name from root, so that it is unique for each path.
- Tested the changes by referencing an extension whose StructureDefinition was not available and ensure proper error message is thrown instead of NPE.
- Ingested an `QuestionnaireResponse` fhir resource and ran a `Full Run` and checked if the `QuestionnaireResponse` is converted to `Avro` record properly
TESTED:
- Added a unit test case
No? Please take some …
> Changes to fix issues of missing extensions and others

- pipelines/batch/src/main/java/com/google/fhir/analytics/FetchSearchPageFn.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/FhirEtl.java
- pipelines/common/src/main/java/com/google/fhir/analytics/ParquetUtil.java
Fixes #1063 by reverting #1047 for non-Dataflow runners. The fix in #1047 made the size of Parqut files a function of Beam's Bundle size which is not a good idea (beside causing #1063 it also impacts the performance of queries on generated Parquet files). So we only do the FinishBundle flush for `DataflowRunner` which tend to have very large Bundle size.
I could force Parquet files to be closed on Dataflow and also avoid #1063 with `DirectRunner` by using `Cleaner` or `finalize()`. That solution is shown in the first commit of this PR but it is a brutal/hacky solution that depends on garbage-collector. So I reverted that fix and went with the conditional `@FinishBundle` idea. We may need to more carefully consider #288 again, i.e., to use `ParquetIO` instead of our own `ParquetUtil` but …
> Fix the issue of DirectRunner generating too many Parquet files.

- cloudbuild.yaml
- docker/compose-controller-spark-sql-single.yaml
- docker/config/application.yaml
- pipelines/controller/config/application.yaml
- pipelines/streaming/pom.xml
With #947 we have enabled sending FHIR resources to a sink server. Turning this on by default, requires an additional setup step of running a sink FHIR server which is not needed for most users (and also is an experimental feature). I am turning this off in the default config but turning it on in e2e since we have tests around it.
TESTED:
Built and ran the docker image locally in the "off case"; relying on e2e for the "on case".
> Turn sinkFhirServerUrl off by default but on in e2e

- doc/Patient_US-Core.schema
- doc/Patient_no-extension.schema
- doc/schema.md
This is the first step for addressing #1025.
TESTED:
NA
> Added the schema doc

- pipelines/controller/pom.xml
- pipelines/controller/src/test/java/com/google/fhir/analytics/FlinkConfigurationTest.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/GcsDwhFilesManagerTest.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/LocalDwhFilesManagerTest.java
Fixes #1085
Controller module unit tests have been migrated to `Junit 5` for proper coverage reporting.
Reference : [Migration to Junit 5](https://junit.org/junit5/docs/current/user-guide/#migrating-from-junit4)
Not Applicable
TESTED:
Verified the coverage report in the codecov before and after the changes, and verified if the numbers now are correct.
> Migrate the unit test annotations to Junit 5

- pipelines/controller/pom.xml
- pipelines/pom.xml
This is to fix the upgrade issue caused by this [PR](https://github.com/google/fhir-data-pipes/pull/927).
The upgrade was failing because the latest Spring code as per this [documentation](https://github.com/spring-projects/spring-framework/wiki/Upgrading-to-Spring-Framework-6.x#parameter-name-retention) needs to know the parameter names (embedded in the compiled classes) and does not deduce the names by parsing the bytecode. The compiler arg `-parameters` is enabled by default for `spring-boot-starter-parent`.
Relied on automated e2e tests.
TESTED:
NA
No? Unsure? -> [configure your …
> Upgrade spring framework to 3.2.2

- pipelines/common/pom.xml
- pipelines/pom.xml
[PR](https://github.com/google/fhir-data-pipes/pull/1090) tries to upgrade `parquet-avro` version, but fails because the other dependent versions like `parquet-common` etc. are inconsistent because of `beam-sdks-java-io-parquet` transitive dependencies.
So we decide to upgrade `parquet-avro` only when `beam-sdks-java-io-parquet` also upgrades `parquet-*` to similar version. Necessary documentation has been added in this PR.
Relied on automated e2e tests.
TESTED:
NA
> Keep `org.apache.parquet:parquet-avro` version consistent with `beam-sdks-java-io-parquet` dependencies

- pipelines/common/src/main/java/com/google/fhir/analytics/DwhFiles.java
- pipelines/controller/config/application.yaml
- pipelines/controller/src/main/java/com/google/fhir/analytics/DwhFilesManager.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/CloudDwhFilesManagerTest.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/GcsDwhFilesManagerTest.java
Fixes the S3 schema parsing issue in the controller code. This is a piece that was missed in #1066 because I only tested the pipeline code directly (not through the controller).
Fixes #1011.
TESTED:
Ran the controller locally but set the `dwhRootPrefix` to a `s3://` location and checked that parquet files are created both in full and incremental runs (like before this needed `AWS_REGION`, `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` to be set).
> Added s3 in schema parsing

- pipelines/batch/src/main/java/com/google/fhir/analytics/BasePipelineOptions.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/FetchSearchPageFn.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/FhirEtl.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcFetchHapi.java
- pipelines/common/src/main/java/com/google/fhir/analytics/ParquetUtil.java
- pipelines/common/src/test/java/com/google/fhir/analytics/ParquetUtilTest.java
- pipelines/streaming/src/main/java/com/google/fhir/analytics/DebeziumListener.java
Fixes #1089 by adding an option to cache Parquet output and flush in `@FinishBundle`. This solution is limited to the Dataflow runner only because:
- With FlinkRunner, at least in the local mode, the bundle size seems to be huge and [`maxBundleSize`](https://beam.apache.org/documentation/runners/flink/) option does not seem to make any difference.
- In Flink local mode, i.e., when everything is run in a single process, I am not sure if recovery from a worker failure is important (or even properly handled by Flink).
Other outputs seem to be fine because:
- We use `PUT` for sending resources to a sink FHIR server.
- Updating views output in a sink DB, handles deletion of old rows.
TESTED:
Ran some Dataflow runs and made sure that there are several bundles per worker. A sample run is …
> Added cacheBundleForParquetWrites option

- pipelines/controller/src/main/java/com/google/fhir/analytics/ApiController.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
- pipelines/controller/src/main/resources/templates/index.html
Currently to retrieve the error log file associated with the latest pipeline run, we pass the log file path in the request as a path parameter, this is prone to vulnerability attacks as there are no checks to restrict the paths only to the data-warehouse directory.
This PR contains changes to remove the path parameter altogether and only retrieves the error log associated with the latest pipeline run if exists.
Tested the changed api and it works as expected. Also, the path parameter to accept file path is no more valid.
TESTED:
relied on e2e tests.
No? Unsure? -> [configure your …
> Remove path variable when retrieving the error log file.

- pipelines/common/src/main/java/com/google/fhir/analytics/ParquetUtil.java
Quick refactoring to extend the [cache implementation](https://github.com/google/fhir-data-pipes/pull/1131) by @bashir2 to views for View-to-Parquet.
TESTED:
> Added Caching for View-to-Parquet writes

- pipelines/batch/src/main/java/com/google/fhir/analytics/ConvertResourceFn.java
- pipelines/controller/config/application.yaml
- pipelines/controller/src/main/java/com/google/fhir/analytics/HiveTableManager.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
Fixes #1140 
This should fix an edge case reported in #1140 where it seems a canonical table is being queried between `DROP` and `CREATE`; see that issue for more details.
The multiple commits on this PR are to show different solutions I tried, e.g.,
- `ALTER TABLE`
- Transactions
- `VIEW`
TESTED:
Ran the controller locally against a local Thrift server and tested various scenarios.
> Change canonical tables to views

- pipelines/common/src/main/java/com/google/fhir/analytics/DwhFiles.java
- pipelines/common/src/test/java/com/google/fhir/analytics/GcsDwhFilesTest.java
- pipelines/common/src/test/java/com/google/fhir/analytics/LocalDwhFilesTest.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/DataProperties.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/DwhFilesManager.java
- pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/CloudDwhFilesManagerTest.java
- pipelines/controller/src/test/java/com/google/fhir/analytics/LocalDwhFilesManagerTest.java
The bug was discovered as part of [this report](https://github.com/google/fhir-data-pipes/issues/1011#issuecomment-2259752302) (see item 4). The actual bug is _not_ what is reported there but for whatever [other] reasons, an incremental-run has failed. That failure has blocked the following incremental-runs (which are supposed to repeat the old failed one). The reason this edge-case fails on cloud files-systems (e.g., GCS, S3), is because there is not really a concept of "directory" there. We have buckets and files in them. As a consequence of this bug-fix, the `incremental_run` directories now have a timestamp suffix as well.
TESTED:
Beside updating unit-tests, I rant the controller locally with  `dwhRootPrefix` set to a `s3://...` path; then created an artificial failure by creating an …
> Fixed an edge case for incremental run failures on cloud file-systems

- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/AvroConverterMergeTest.java
- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/R4AvroConverterUsCoreTest.java
- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/Stu3AvroConverterUsCoreTest.java
- bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/TestUtil.java
- bunsen/bunsen-core-r4/src/test/java/com/cerner/bunsen/r4/TestData.java
- bunsen/bunsen-core-stu3/src/test/java/com/cerner/bunsen/stu3/TestData.java
> Updates tests for converter idempotency

- pipelines/batch/src/main/java/com/google/fhir/analytics/ConvertResourceFn.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcFetchHapi.java
- pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcResourceWriter.java
- pipelines/batch/src/test/java/com/google/fhir/analytics/JdbcResourceWriterTest.java
- pipelines/common/src/main/java/com/google/fhir/analytics/FhirStoreUtil.java
- pipelines/common/src/test/java/com/google/fhir/analytics/FhirStoreUtilTest.java
Fixes #588 
Delete the FHIR resources in the Sink DB and Sink FHIR servers during export.
Relied on e2e tests.
TESTED:
Manually tested by deleting the resources from the source FHIR server and verifying the same from the sink systems.
> Delete resources in the sink DB and FHIR server

- bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/AvroConverter.java
- bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java
- bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/PrimitiveConverter.java
- bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/StructureDefinitions.java
- bunsen/pom.xml
- pipelines/common/src/test/java/com/google/fhir/analytics/view/SQLonFHIRv2Test.java
- pipelines/pom.xml
For why we are doing this, see #1014 and in particular [this comment](https://github.com/google/fhir-data-pipes/issues/1014#issuecomment-2455453171).
TESTED:
Relied on unit/e2e tests.
> Advances hapi versions and skips xhtml fields

- pipelines/batch/pom.xml
- pipelines/common/pom.xml
- pipelines/common/src/test/java/com/google/fhir/analytics/ParquetUtilTest.java
- pipelines/pom.xml
- pipelines/streaming/pom.xml
This change reduces the size of a `mvn clean package` output by over 20K lines by preventing [this](https://github.com/apache/parquet-java/blob/fb6f0be0323f5f52715b54b8c6602763d8d0128d/parquet-hadoop/src/main/java/org/apache/parquet/hadoop/InternalParquetRecordWriter.java#L203).
TESTED:
Ran the tests locally and checked log size.
> Removed long WARN logs

- pipelines/common/pom.xml
Reverts google/fhir-data-pipes#1301
This seems to have made the build more flaky as a lot of e2e builds failed after this (but some passed too!) It is also a `pre` version, so maybe it is better to revert.
> Revert "Bump com.mchange:c3p0 from 0.10.2 to 0.11.0-pre2"
