google/fhir-data-pipes

.travis.yml, pom.xml
=> added Travis config

batch/src/main/java/org/openmrs/analytics/FhirEtl.java, batch/src/main/java/org/openmrs/analytics/FhirSearchUtil.java, batch/src/main/java/org/openmrs/analytics/SearchSegmentDescriptor.java, common/src/main/java/org/openmrs/analytics/FhirStoreUtil.java, common/src/test/java/org/openmrs/analytics/FhirStoreUtilTest.java, pom.xml, streaming/pom.xml, streaming/src/main/java/org/openmrs/analytics/FeedConsumer.java, streaming/src/main/java/org/openmrs/analytics/FhirEventWorker.java, streaming/src/main/java/org/openmrs/analytics/FhirStreaming.java, streaming/src/test/java/org/openmrs/analytics/FhirEventWorkerTest.java
=> Added code formatting plugins.

README.md, batch/pom.xml, batch/src/main/java/org/openmrs/analytics/FhirEtl.java, batch/src/main/java/org/openmrs/analytics/FhirSearchUtil.java, batch/src/main/java/org/openmrs/analytics/SearchSegmentDescriptor.java, common/pom.xml, common/src/main/java/org/openmrs/analytics/FhirStoreUtil.java, common/src/main/java/org/openmrs/analytics/OpenmrsUtil.java, common/src/test/java/org/openmrs/analytics/FhirStoreUtilTest.java, common/src/test/java/org/openmrs/analytics/OpenmrsUtilTest.java, pom.xml, streaming-binlog/src/main/java/org/openmrs/analytics/PipelineSink.java, streaming/pom.xml, streaming/src/main/java/org/openmrs/analytics/FeedConsumer.java, streaming/src/main/java/org/openmrs/analytics/FhirEventWorker.java, streaming/src/main/java/org/openmrs/analytics/FhirStreaming.java, utils/fhir2_atom_feed_config.json
Closes #4 
Tested the atomfeed streaming pipeline against an OpenMRS instance and verified that the output resources are as expected in BigQuery.
=> Add BasicAuth authentication for OpenMRS requests for #4

batch/src/main/java/org/openmrs/analytics/FhirSearchUtil.java, batch/src/main/java/org/openmrs/analytics/SearchSegmentDescriptor.java, batch/src/main/resources/log4j2.xml, common/src/main/resources/log4j2.xml, common/src/test/java/org/openmrs/analytics/FhirStoreUtilTest.java, common/src/test/java/org/openmrs/analytics/OpenmrsUtilTest.java, license-format.xml, license-header.txt, pom.xml, streaming-binlog/src/main/resources/log4j2.xml, streaming/src/main/java/org/openmrs/analytics/FhirEventWorker.java, streaming/src/main/resources/atomfeed.properties, streaming/src/main/resources/hibernate.default.properties, streaming/src/main/resources/log4j2.xml
=> Add automatic license header generation

README.md, docker-compose.yaml, streaming-binlog/pom.xml, streaming-binlog/src/main/java/org/openmrs/analytics/FhirUriGenerator.java, streaming-binlog/src/main/java/org/openmrs/analytics/PipelineConfig.java, streaming-binlog/src/test/java/org/openmrs/analytics/DebeziumListenerTest.java, streaming-binlog/src/test/java/org/openmrs/analytics/FhirUriGeneratorTest.java, utils/dbz_event_to_fhir_config.json, utils/fhir2_atom_feed_config.json
reused fhir2_atom_feed_config.json as well as some service in fhir_atom_fhir module
=> Make the events to FHIR generator configurable #23

streaming/src/main/java/org/openmrs/analytics/FhirStreaming.java, utils/fhir2_atom_feed_config.json
Corrected Source FhirURL to R3 ,Since we are implementing version R3 of Fhir because of Bunsen limitation
=> correct FhirUrl version to R3

batch/src/main/java/org/openmrs/analytics/FhirEtl.java, common/pom.xml, common/src/main/java/org/openmrs/analytics/ParquetUtil.java, common/src/test/java/org/openmrs/analytics/ParquetUtilTest.java, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java, streaming-binlog/src/main/java/org/openmrs/analytics/FhirConverter.java, streaming-binlog/src/main/java/org/openmrs/analytics/Runner.java, streaming-binlog/src/test/java/org/openmrs/analytics/DebeziumListenerTest.java, streaming-binlog/src/test/java/org/openmrs/analytics/FhirConverterTest.java
=> Added writing to Parquet in the debezium pipeline.

.gitignore, README.md, dwh/sample_indicator.py, streaming-binlog/src/main/java/org/openmrs/analytics/FhirConverter.java
Tested:
I ran the queries using the documented usage in README on Parquet files generated by the batch pipeline. I also compared the results of SQL based with DataFrame based approaches.
=> Sample queries on Parquet files using pyspark

.gitignore, README.md, batch/pom.xml, batch/src/main/java/org/openmrs/analytics/FhirEtl.java, common/pom.xml, common/src/main/java/org/openmrs/analytics/BaseArgs.java, common/src/main/java/org/openmrs/analytics/FhirStoreUtil.java, common/src/main/java/org/openmrs/analytics/ParquetUtil.java, common/src/test/java/org/openmrs/analytics/ParquetUtilTest.java, pom.xml, streaming-atomfeed/pom.xml, streaming-atomfeed/src/main/java/org/openmrs/analytics/FhirStreaming.java, streaming-binlog/pom.xml, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java, streaming-binlog/src/main/java/org/openmrs/analytics/FhirConverter.java, streaming-binlog/src/main/java/org/openmrs/analytics/Runner.java, streaming-binlog/src/test/java/org/openmrs/analytics/DebeziumListenerTest.java, streaming-binlog/src/test/java/org/openmrs/analytics/FhirConverterTest.java
Issue : #21
TESTED
tested with
```
--databasePort=3308 --databaseUser=root --databasePassword=Admin123\
--databaseName=mysql --databaseSchema=openmrs --databaseServerId=223344 \
--openmrsServerUrl=http://localhost:8080 \
--fhirSinkPath=http://localhost:8099/ \
--sinkUser=hapi --sinkPassword=hapi "
mvn compile  exec:java -pl streaming-atomfeed \
-Dexec.args=" --openmrsUserName=admin --openmrsPassword=Admin123 \
--openmrsServerUrl=http://localhost:8080 \
--fhirSinkPath=http://localhost:8099 \
--sinkUser=hapi --sinkPassword=hapi "
mvn exec:java -pl batch \
"-Dexec.args=--serverUrl=http://localhost:8080  --searchList=Observation \
--batchSize=20 …
```
=>  standadize argument passing using commandline args

README.md, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java
By default, the pipeline will take a snapshot of the database. However, we need an override mechanism for this behavior,
as such, I have added a new option that can be used to turn this feature on/off.  Please see this issue: https://github.com/GoogleCloudPlatform/openmrs-fhir-analytics/issues/69
TESTED:
No? …
=> Add the ability to turn on/off snapshotMode of debezium #69

README.md
=> correct server url in the readme

sink-compose.yml
Added `docker-compose` setup for a sink FHIR server using https://github.com/hapifhir/hapi-fhir-jpaserver-starter.  
N/A
=> Adding sink FHIR server docker config to close #77

README.md, common/src/main/java/org/openmrs/analytics/BaseArgs.java, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java
TESTED:
Tested Both with and  without the arg --fileParquetPath=/tmp/   passed 
```
--databasePort=3308 --databaseUser=root --databasePassword=Admin123\
--databaseName=mysql --databaseSchema=openmrs --databaseServerId=223344 \
--openmrsServerUrl=http://localhost:8080 \
--fhirSinkPath=http://localhost:8088/fhir \
--sinkUser=hapi --sinkPassword=hapi123 " 
```
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and …
=> minor fix in params

docker-compose.yaml
=> Fixed docker mount path issue for dbz_event_to_fhir_config.json file

common/src/main/java/org/openmrs/analytics/FhirStoreUtil.java, common/src/main/java/org/openmrs/analytics/GcpStoreUtil.java, common/src/test/java/org/openmrs/analytics/FhirStoreUtilTest.java, common/src/test/resources/patient_bundle.json, common/src/test/resources/patient_response_bundle.json
Supports uploading resources to a FHIR endpoint via transaction bundles.
This also fixes a TODO to only remove the SUBSETTED tag and leave the others.
TESTED:
I have not yet actually done an e2e test …
=> Support uploading resources via transaction bundles

README.md, openhim-compose.yaml, utils/openhim-config.json, utils/openhim-default.json
TESTED:
mvn compile exec:java -pl batch \
"-Dexec.args=--openmrsServerUrl=http://localhost:8081/openmrs  --searchList=Patient,Observation \
--batchSize=20 --targetParallelism=20  \
--fhirSinkPath=http://localhost:5001/fhir \
--sinkUserName=hapi --sinkPassword=Admin123 \
--openmrsUserName=admin --openmrsPassword=Admin123 "
No? -> write tests and add them to this commit `git add . && git …
=> intergrate OpenHIM into the Pipeline

.gitignore, README.md, dwh/sample_indicator.py, dwh/test_spark.ipynb
TESTED:
Ran all of the steps against a Jupyter server.
Separate unit-tests do not apply for this case as everything is tested in a notebook and the results are recorded.
=> Added a sample Jupyter notebook.

common/src/main/java/org/openmrs/analytics/FhirStoreUtil.java, common/src/test/java/org/openmrs/analytics/FhirStoreUtilTest.java
TESTED:
//debezium
```
--databasePort=3308 --databaseUser=root --databasePassword=Admin123 \
--databaseServerId=223344 \
--openmrsServerUrl=http://localhost:8081/openmrs \
--fhirSinkPath=http://localhost:5001/fhir \
--openmrsfhirBaseEndpoint=/ws/fhir2/R4 \
--snapshotMode=when_needed\
--sinkUserName=hapi --sinkPassword=Admin123 "
```
//atom feed   
```
mvn exec:java -pl streaming-atomfeed \
-Dexec.args=" --openmrsUserName=admin --openmrsPassword=Admin123 \
--openmrsServerUrl=http://localhost:8081/openmrs \
--fhirSinkPath=http://localhost:5001/fhir \
--sinkUserName=hapi --sinkPassword=Admin123 "
```
//batch
```
mvn compile exec:java -pl batch \ …
```
=> Change Post To PUT When Uploading to a Generic Fhir Store

README.md, docker-compose.yaml, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java, streaming-binlog/src/main/java/org/openmrs/analytics/model/EventConfiguration.java, streaming-binlog/src/main/java/org/openmrs/analytics/model/GeneralConfiguration.java, streaming-binlog/src/test/java/org/openmrs/analytics/DebeziumListenerTest.java, utils/dbz_event_to_fhir_config.json
TESTED:
-Dexec.args="--openmrsUserName=admin --openmrsPassword=Admin123 \
--openmrsServerUrl=http://localhost:8081/openmrs \
--fhirSinkPath=http://localhost:8888/fhir \
--openmrsfhirBaseEndpoint=/ws/fhir2/R4 \
--sinkUserName=hapi --sinkPassword=hapi123 "
`Created a Patient in OpenMRS and validated it is being propagated to the hapi fhir server`
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and [Python](https://google.github.io/styleguide/pyguide.html) style guides. Note, when in conflict, OpenMRS style guide …
=> followup fix for  #51

utils/dbdump/fhir_concept_sources.sql
TESTED:
spinned up the openmrs docker instance and requested a fhir Observation Resource
=> Populate fhir concept source systems from the sql dump file  #110

batch/src/main/java/org/openmrs/analytics/FhirEtl.java, batch/src/main/java/org/openmrs/analytics/JdbcFetchUtil.java
Fixes #92 
As reported in #92 generating Parquet files in the JDBC mode was taking too long. This PR fixes it by setting the number of shards specifically. This change seems to fix the issue as noted in the TESTED field below (the root cause to be determined yet).
TESTED:
Ran the pipeline in both FHIR-search and JDBC modes; the latter used to be an order of magnitude slower but now:
**JDBC:**
```
java -cp batch/target/fhir-batch-etl-bundled-0.1.0-SNAPSHOT.jar org.openmrs.analytics.FhirEtl \\
--openmrsServerUrl=http://localhost:8099/openmrs --jdbcUrl=jdbc:mysql://localhost:3306/openmrs \\
--jdbcFetchSize=1000  --jdbcMaxPoolSize=100 --jdbcModeEnabled \\
--targetParallelism=10 --numParquetShards=5  --fileParquetPath=[PATH]
```
takes ~15 minutes (setting number of shards to 10 does not help). …
=> Fixes the Parquet sharding issue, plus some related refactorings.

batch/Dockerfile, batch/pom.xml, docker-compose.yaml, pom.xml, streaming-binlog/Dockerfile, streaming-binlog/pom.xml, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java, streaming-binlog/src/main/java/org/openmrs/analytics/UuidUtil.java, streaming-binlog/src/test/java/org/openmrs/analytics/UuidUtilTest.java, utils/dbz_event_to_fhir_config.json
Add docker config entry for the streaming mode #27 
TESTED:
`docker-compose-up --build streaming-binlog batch`
Ensured that
-  both the batch and streaming pipeline can write  parquet in one folder
- when using the `schema_only` snapshot mode, the pipeline is able to capture only new events (created some vitals using OMRS) 
- when using the `default` snapshot mode, the pipeline is able to capture all the records and write parquet files
mvn exec:java -pl streaming-binlog
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and …
=> Add docker-config entry for streaming #27

batch/src/main/java/org/openmrs/analytics/JdbcFetchUtil.java, common/src/main/java/org/openmrs/analytics/JdbcConnectionUtil.java, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java, streaming-binlog/src/main/java/org/openmrs/analytics/FhirConverter.java, streaming-binlog/src/main/java/org/openmrs/analytics/UuidUtil.java, streaming-binlog/src/test/java/org/openmrs/analytics/FhirConverterTest.java, streaming-binlog/src/test/java/org/openmrs/analytics/UuidUtilTest.java
This should make no functional changes (although regeneration of `comboPooledDataSource` in the old version of `JdbcConnectionUtil.getConnectionObject` in #86 might have had some performance implications and potentially some race condition issues which are resolved now).
TESTED:
Didn't do any manual tests as I do not expect functional changes.
No? -> write tests and add them to this …
=> Minor clean-up follow-ups for #86

batch/src/main/java/org/openmrs/analytics/JdbcFetchUtil.java, batch/src/test/java/org/openmrs/analytics/JdbcFetchUtilTest.java
TESTED:
mvn compile exec:java -pl batch \
-Dexec.args="--openmrsServerUrl=http://localhost:8081/openmrs \
--fhirSinkPath=http://localhost:8080/fhir \
--sinkUserName=hapi --sinkPassword=hapi123 \
--searchList=Patient,Person --batchSize=20 \
--jdbcModeEnabled=true --jdbcUrl=jdbc:mysql://localhost:3306/openmrs \
--dbUser=root --dbPassword=Admin123 --jdbcMaxPoolSize=50 \
--jdbcDriverClass=com.mysql.cj.jdbc.Driver"  
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and …
=> minor fix , to fetch uuid coresponding to max_id and avoid generating repetitive lower range value

utils/create_fhir_store.sh
Function for creating datasets with error handling in case dataset exists
TESTED:
Ran a command twice: `utils/create_fhir_store.sh PROJECT_NAME us-central1 test_data openmrs-relay`  
First time it created the dataset, second time it said that dataset already exists.
No? -> figure out why and add the fix to …
=> Function for creating datasets with error handling in case dataset exists

README.md, batch/src/main/java/org/openmrs/analytics/EtlUtils.java, batch/src/main/java/org/openmrs/analytics/FetchPageSearchFn.java, batch/src/main/java/org/openmrs/analytics/FhirEtl.java, batch/src/main/java/org/openmrs/analytics/FhirEtlOptions.java, batch/src/main/java/org/openmrs/analytics/FhirSearchUtil.java, batch/src/test/java/org/openmrs/analytics/JdbcFetchUtilTest.java, common/src/main/java/org/openmrs/analytics/BaseArgs.java, common/src/main/java/org/openmrs/analytics/ParquetUtil.java, docker-compose.yaml, e2e-tests/batch-mode-tests.sh, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java, streaming-binlog/src/main/java/org/openmrs/analytics/UuidUtil.java, streaming-binlog/src/test/java/org/openmrs/analytics/UuidUtilTest.java
In many debugging scenarios, it is handy to be able to generate JSON output too. The latest incident was for debugging #136 so I decided to properly implement this. Since this might be later useful in non-test scenarios too, this implementation supports both JSON and Parquet generation at the same time.
I also did some refactoring of the code because of this change since `FhirEtl.java` was getting too big (and non-unit-tested). Will add unit-tests in a follow-up PR.
TESTED:
Ran:
```
java -cp batch/target/fhir-batch-etl-bundled-0.1.0-SNAPSHOT.jar org.openmrs.analytics.FhirEtl \
--openmrsServerUrl=http://localhost:8099/openmrs --jdbcUrl=jdbc:mysql://localhost:3306/openmrs \
--searchList=Patient --jdbcFetchSize=1000  --jdbcMaxPoolSize=100 --jdbcModeEnabled --targetParallelism=10 \ …
```
=> Added JSON output option with some refactoring.

README.md, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java, streaming-binlog/src/main/java/org/openmrs/analytics/model/EventConfiguration.java, utils/dbz_event_to_fhir_config.json
Fixes #125
TESTED: Ran Debezium pipeline to FHIR server against Docker OpenMRS and HAPI FHIR containers.
=> Fix debezium parameters

batch/Dockerfile, batch/src/main/java/org/openmrs/analytics/FhirEtl.java, docker/docker-compose.yaml
Rename numParquetShards parameter to numFileShards #153 
TESTED:
`docker-compose -f docker/docker-compose.yaml up --build batch`
=> Rename numParquetShards parameter to numFileShards #153

batch/pom.xml, common/pom.xml
This updates the parquet-avro and Beam dependency versions; it also drops the parquet dependency through Beam since we don't use ParquetIO anymore. One motivation for this change is #168.
TESTED:
Just the usual unit/e2e tests.
NA
No? Unsure? -> execute command `git pull --rebase …
=> Updated parquet-avro and beam versions

batch/src/main/java/org/openmrs/analytics/FetchPatientHistory.java, batch/src/main/java/org/openmrs/analytics/FetchResources.java, batch/src/main/java/org/openmrs/analytics/FhirEtl.java, batch/src/main/java/org/openmrs/analytics/JdbcFetchUtil.java, batch/src/test/java/org/openmrs/analytics/FetchResourcesTest.java, common/src/main/java/org/openmrs/analytics/ParquetUtil.java, common/src/test/java/org/openmrs/analytics/ParquetUtilTest.java, streaming-binlog/src/main/java/org/openmrs/analytics/DebeziumListener.java, streaming-binlog/src/main/java/org/openmrs/analytics/FhirConverter.java, streaming-binlog/src/main/java/org/openmrs/analytics/StatusServer.java, streaming-binlog/src/test/java/org/openmrs/analytics/FhirConverterTest.java, streaming-binlog/src/test/java/org/openmrs/analytics/StatusServerTest.java, utils/start_pipelines.sh
The is the second part of #151 where a script is added to run the streaming pipeline and optionally start a batch pipeline that is synchronized with the streaming pipeline. The batch pipeline fetches resources older than streaming pipeline start time.
TESTED:
Sample run:
```
./utils/start_pipelines.sh -o data/OUT -secondsToFlushStreaming 20 -b -s
```
created new resources and verified output.
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and [Python](https://google.github.io/styleguide/pyguide.html) style guides. Note, when in conflict, OpenMRS style guide …
=> Added pipeline start script with other relevant changes

dwh/indicator_lib.py, dwh/validate_indicators.sh
Addresses the proportions/ratio [TODO](https://github.com/GoogleCloudPlatform/openmrs-fhir-analytics/blob/master/dwh/indicator_lib.py#L90) here https://github.com/GoogleCloudPlatform/openmrs-fhir-analytics/blob/master/dwh/indicator_lib.py#L90
TESTED:
No? -> figure out why and add the fix to your commit. It …
=> Add proportions back and fix  aggregation bracket not showing

dwh/indicator_lib.py, dwh/indicators.py
Handle all types of date format in the indicator calculation logic #174 
TESTED:
=> Handle all types of date format in the indicator calculation logic #174

bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java, bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/EnumConverter.java, bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/IdConverter.java, bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/StringConverter.java, bunsen/bunsen-core/src/test/java/com/cerner/bunsen/definitions/IdConverterTest.java, bunsen/pom.xml, pipelines/common/src/test/java/org/openmrs/analytics/ParquetUtilTest.java
This fixes issue #55 (also [this Bunse issue](https://github.com/cerner/bunsen/issues/106)); it is a better version of [this original Bunsen PR](https://github.com/cerner/bunsen/pull/111) that was never reviewed/merged.
TESTED:
Unit-tests added
No? -> figure out why and add the fix to your commit. It is your …
=> fixed ID conversion to keep IdPart only

pipelines/batch/pom.xml, pipelines/common/pom.xml, pipelines/pom.xml
TESTED:
Just relied on automated unit and e2e tests.
NA
=> updated log4j version to 2.15.0

pipelines/pom.xml
=> Update log4j to 2.16.0

pipelines/pom.xml
=> updated openmrsPlatformVersion to get rid of the remaining log4j v2.15

pipelines/README.md, pipelines/batch/pom.xml, pipelines/pom.xml
Added Flink runner in the default build and made recommendations for using it in the README for large datasets. This is because Direct runner is not recommended for production runs (and we know it has memory/fusion issues).
The increase in the uber jar size was from ~178 MB (without Flink) to ~220 MB.
Also repeated the test run in PR #230 and as expected using Flink runner did not make huge difference; with Direct runner it took ~140 mins, with Flink runner it took ~138 mins (this is because most of the time is spent in FHIR resource conversions).
TESTED:
Ran with "big" test database as described above:
```
$ java -cp ./pipelines/batch/target/batch-bundled-0.1.0-SNAPSHOT.jar org.openmrs.analytics.FhirEtl --fhirDebeziumConfigPath=./utils/dbz_event_to_fhir_config.json …
```
=> Added flink in the default build

cloudbuild.yaml, synthea-hiv/uploader/Dockerfile, synthea-hiv/uploader/main.py
Make number of processes variable for uploader
TESTED:
N/A
=> Make number of processes variable for uploader

docker/sink-compose.yml
I disabled the 'mdm_enabled' flag in the docker file for the HAPI server. This disables the generation of 'golden' resources and allows the usage of the latest release of HAPI while passing e2e tests.
Fixes #259.
TESTED:
No? -> figure out why and add the fix to your commit. It is your responsibility to make …
=> Disabled MDM linking in HAPI server (#259)

doc/openhim.md, docker/docker-compose.yaml, e2e-tests/pipeline_validation.sh, e2e-tests/wait_for_start.sh, e2e-tests/wait_for_streaming.sh, pipelines/README.md, pipelines/batch/Dockerfile, pipelines/batch/src/main/java/org/openmrs/analytics/FetchSearchPageFn.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtl.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtlOptions.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirSearchUtil.java, pipelines/batch/src/test/java/org/openmrs/analytics/JdbcFetchUtilTest.java, pipelines/common/src/main/java/org/openmrs/analytics/BaseArgs.java, pipelines/streaming/Dockerfile, pipelines/streaming/src/main/java/org/openmrs/analytics/DebeziumListener.java, pipelines/streaming/src/test/java/org/openmrs/analytics/DebeziumListenerTest.java, synthea-hiv/uploader/main.py, utils/start_pipelines.sh
Merged the fhir source url flags _openmrsServerUr_ and _openmrsFhirBaseEndpoint_ into the single flag _fhirServerUrl_ and refactored the underlying flag logic in the pipelines code. 
Enabled HAPI as a source for batch mode and documented the sample command in the ./pipelines READ.me file. This partly addresses issue #265, ensuring the FHIR-search based mode for the batch pipeline works with HAPI as a source. 
TESTED:
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and [Python](https://google.github.io/styleguide/pyguide.html) style guides. Note, when in conflict, …
=> Merged server url flags and enabled HAPI source for batch mode

pipelines/batch/pom.xml, pipelines/pom.xml
Upgrades few packages fixed the issue.
TESTED:
=> Upgrading the package dependency versions to fix test exceptions.

bunsen/pom.xml, pipelines/batch/pom.xml, pipelines/common/pom.xml, pipelines/common/src/main/java/org/openmrs/analytics/GcpStoreUtil.java, pipelines/pom.xml, utils/merge_all_dependabot_PRs.sh
This merges dependabot commits and adds a little tool for making this easier to do in future.
The HAPI upgrade feature was reverted because it needs some more "converter" related changes.
TESTED:
NA
For this PR, I did not merge the commits as those are all separate commits automatically generated by dependabot.
=> Merged dependabot commits with minor changes

bunsen/bunsen-avro/pom.xml, bunsen/bunsen-core-stu3/pom.xml, bunsen/bunsen-core-stu3/src/main/java/com/cerner/bunsen/definitions/stu3/Stu3StructureDefinitions.java, bunsen/bunsen-core/pom.xml, bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/StructureDefinitions.java, bunsen/bunsen-uscore-resources-stu3/src/main/java/com/cerner/bunsen/stu3/UsCoreStu3ProfileProvider.java, bunsen/bunsen-uscore-resources-stu3/src/test/java/com/cerner/bunsen/test/profiles/stu3/BunsenTestStu3ProfileProvider.java, bunsen/pom.xml, pipelines/batch/src/main/java/org/openmrs/analytics/FetchSearchPageFn.java, pipelines/common/src/main/java/org/openmrs/analytics/ParquetUtil.java, pipelines/pom.xml
Upgraded HAPI version to 6.1.1 with some required modifications (and a related one that came up in a recent review).
TESTED:
Relied on the e2e tests.
=> Upgraded HAPI version to 6.1.1 with required modifications

docker/hapi-compose.yml
Enables the bulk export feature in our docker-compose config.
TESTED:
I have tested this feature in H2 DB mode and it works but it fails in the PostgreSQL mode; details:
https://chat.fhir.org/#narrow/stream/179167-hapi/topic/Exception.20during.20.24export
=> enabled bulk export

pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtl.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtlOptions.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirSearchUtil.java, pipelines/batch/src/main/java/org/openmrs/analytics/JdbcFetchHapi.java
TESTED:
I tested this manually by adding a new resource and checking that `--since` forces that single resource to be fetched.
```
java -cp ./pipelines/batch/target/batch-bundled-0.1.0-SNAPSHOT.jar org.openmrs.analytics.FhirEtl \
--jdbcDriverClass=org.postgresql.Driver --fhirDatabaseConfigPath=utils/hapi-postgres-config_local.json \
--jdbcModeEnabled --jdbcModeHapi --fhirServerUrl=http://localhost:8092/fhir \
--resourceList=Patient --outputParquetPath=[PATH] --since=2022-10-31T16:00:00
```
The base code that is changed lacks proper unit-tests (because of DB …
=> added --since option

pipelines/batch/pom.xml
The removed dependencies seem to be left-over from the very first prototype and not used anywhere.
TESTED:
Relied on current e2e/unit tests
=> Removed some unnecessary deps

pipelines/controller/compose-controller-spark-sql.yaml
It seems that since [this change](https://github.com/bitnami/containers/commit/90e3cfe865fbcc370649c64cd786ef1251afd06f) in Bitnami Spark image, we can't run the Thrift server anymore (it has a permission error when creating `/opt/bitnami/spark/metastore_db`). The culprit seems to be removal of `chown -R 1001:root /opt/bitnami/spark` which we need to check with Bitnami team.
This is a temporary fix.
TESTED:
`docker-compose -f compose-controller-spark-sql.yaml up`
No? Unsure? ->
[configure your IDE](https://github.com/google/google-java-format).
added all …
=> Temporary switch to image spark:3.3.1-debian-11-r19

bunsen/pom.xml, pipelines/batch/pom.xml, pipelines/common/pom.xml, pipelines/common/src/main/java/org/openmrs/analytics/GcpStoreUtil.java, pipelines/controller/pom.xml, pipelines/pom.xml, pipelines/streaming/pom.xml
I ran [merge_all_dependabot_PRs.sh](https://github.com/google/fhir-data-pipes/blob/master/utils/merge_all_dependabot_PRs.sh) to extract all commits (but needed to make some modifications to the script; will send in a separate PR).
TESTED:
Relied on unit/e2e test.
**NOTE:** This intentionally has multiple PRs that correspond to dependabot ones, plus extra fixes.
=> Combines many dependabot PRs into one

cloudbuild.yaml, e2e-tests/Dockerfile, e2e-tests/pipeline_validation.sh
Added Non Jdbc test for HAPI source
TESTED:
=> Add Non Jdbc test for HAPI source

.dockerignore, Dockerfile, cloudbuild.yaml, docker/.env, docker/compose-controller-spark-sql.yaml, docker/config/application.yaml, docker/config/flink-conf.yaml, docker/config/hapi-postgres-config_local.json, docker/dwh/README.md
This PR makes a few changes to the controller docker config setup:
1) First it fixes #487 by creating a root-level `Dockerfile` which builds all the required pieces.
2) It also moves the `compose-controller-spark-sql.yaml` under `/docker` with required config/dwh default values. This fixes #491 and fixes #492.
3) It documents how to rebuild the controller docker image when running compose (i.e., with `--build`); this fixes #490 (although not exactly what is asked there but a good solution IMHO as forcing a rebuild by default is not great either).
TESTED:
Ran `docker-compose -f compose-controller-spark-sql.yaml up --build` and confirmed that a new docker image is build and new changes are picked up. Also ran a full pipeline run (did not test incremental). We should add tests for this …
=> Changes Dockerfile to build controller and moves compose & config

pipelines/batch/pom.xml, pipelines/common/pom.xml, pipelines/pom.xml
This is automatically created by running `./utils/merge_all_dependabot_PRs.sh`.
TESTED:
Relied on unit/e2e tests.
=> Merges multiple dependabot PRs into one

pipelines/batch/src/main/java/org/openmrs/analytics/ConvertResourceFn.java, pipelines/batch/src/test/java/org/openmrs/analytics/ConvertResourceFnTest.java
Fixes #543 
Ignore the deleted records while migrating the FHIR resources to target location like parquet files/sinkDB. This should work fine for initial batch, but for incremental run we need to delete the corresponding original records from the target location. These changes are yet to made and there is a open ticket for this #547.
TESTED:
Created some Active and Deleted records in the HAPI server and ran the initial batch run. Before the fix, the batch run fails, but after the fix, the pipeline runs successfully.
No? Unsure? -> …
=> Ignore deleted records while migrating FHIR resources

bunsen/pom.xml, pipelines/batch/pom.xml, pipelines/common/pom.xml, pipelines/controller/pom.xml, pipelines/pom.xml, pipelines/streaming/pom.xml
This is created by running `utils/merge_all_dependabot_PRs.sh` followed by some manual version downgrades (as they broke the build).
TESTED:
Relying on e2e tests.
=> Merge multiple dependabot PRs

pipelines/batch/src/main/java/org/openmrs/analytics/ConvertResourceFn.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtl.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtlOptions.java, pipelines/batch/src/main/java/org/openmrs/analytics/HapiRowDescriptor.java, pipelines/batch/src/main/java/org/openmrs/analytics/JdbcFetchHapi.java, pipelines/batch/src/main/java/org/openmrs/analytics/ParquetMerger.java, pipelines/batch/src/test/java/org/openmrs/analytics/ConvertResourceFnTest.java, pipelines/batch/src/test/java/org/openmrs/analytics/JdbcFetchHapiTest.java, pipelines/common/src/main/java/org/openmrs/analytics/JdbcConnectionUtil.java, pipelines/controller/src/main/java/org/openmrs/analytics/ApiController.java, pipelines/controller/src/main/java/org/openmrs/analytics/PipelineManager.java
This PR is to fix the issue #547. The below changes have been made part of the PR
- During incremental run, identify the number of resources to be fetched using JDBC query instead of FHIR search API
- Persist the deleted record into parquet file with a meta.tag identifier set to an constant ActionType.REMOVE
- During merge process remove the original record from the merged file using this deleted record.
TESTED:
After the initial batch is triggered, few FHIR records like Encounter, Patient were deleted from HAPI server and then the incremental pipeline is triggered from the UI control panel. Before the fix, pipeline ignored the deleted records and did not remove the merged parquet, after the fix the original gets removed from the merged file. …
=> Changes to process the deleted records during incremental run

Dockerfile, bunsen/pom.xml, cloudbuild.yaml, pipelines/batch/Dockerfile, pipelines/common/pom.xml, pipelines/common/src/main/java/org/openmrs/analytics/DwhFiles.java, pipelines/common/src/main/java/org/openmrs/analytics/model/DatabaseConfiguration.java, pipelines/controller/pom.xml, pipelines/pom.xml
All of the commits except the last one, are auto-generated using `./utils/merge_all_dependabot_PRs.sh`. The last commit is a manual one in which I have upgraded some of the versions that are compatible with Java 17+ (which we avoided before).
TESTED:
Relied on unit/e2e tests; there is another PR on top of this which updates the HAPI server version for which I am doing more manual tests.
=> Dep version upgrades

pipelines/batch/src/main/java/org/openmrs/analytics/ConvertResourceFn.java, pipelines/batch/src/main/java/org/openmrs/analytics/FetchResources.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtl.java, pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtlOptions.java, pipelines/batch/src/main/java/org/openmrs/analytics/JdbcFetchHapi.java, pipelines/batch/src/test/java/org/openmrs/analytics/ConvertResourceFnTest.java, pipelines/controller/config/application.yaml, pipelines/controller/src/main/java/org/openmrs/analytics/DataProperties.java, pipelines/controller/src/main/java/org/openmrs/analytics/PipelineManager.java
This fixes #630 by counting number of resources directly from DB (through JDBC) instead of depending on FHIR search. This also adds an option for setting number of threads for more control on parallelism.
TESTED:
Ran the controller locally with `fhirServerUrl` set to empty string then tested full and incremental modes.
=> Removed dependence on FHIR search in JDBC mode

pipelines/README.md, pipelines/controller/README.md
Fix broken relative links
TESTED:
N/A
=> Fix broken links

pipelines/batch/src/main/java/org/openmrs/analytics/FhirEtl.java
Instead of logging the metrics in parallel during the pipeline run, they are logged sequentially so that the worker threads are not split.
Fixes #667 
TESTED:
The pipeline batch run is tested before and after the fixes. Below are the statistics.
Testing is made on a 24 core machine for 8K patients.
Scenario 1: Without progress bar changes, time taken ~ 10 minutes 
Scenario 2: With progress bar changes, no fix, time taken ~ 13 minutes  
Scenario 3: With progress bar changes, with fix, time taken ~ 10 minutes  
With the fix made, the time taken now is almost the same as earlier.
No? Unsure? -> [configure your …
=> Fix performance issue in progress bar

bunsen/pom.xml, pipelines/batch/pom.xml, pipelines/common/pom.xml, pipelines/controller/pom.xml, pipelines/pom.xml, pipelines/streaming/pom.xml
Merged Dependabot changes.
N/A
TESTED:
Made sure there are no compilation errors.
=> Dependabot merges

Dockerfile, docker/compose-controller-spark-sql-single.yaml, docker/compose-controller-spark-sql.yaml, pipelines/controller/src/main/java/org/openmrs/analytics/PipelineManager.java
This adds some default memory values to the docker image to make sure the JVM has enough memory. It also used to have some changes to switch to using `compose-controller-spark-sql-single.yaml` which is now covered by PR #726.
TESTED:
Ran `compose-controller-spark-sql-single.yaml` locally and did a full run; then checked the tables in thrift-server.
=> Added default memory values and other minor docker changes

docker/compose-controller-spark-sql-single.yaml
This is just a comment to help people skip the build and instead use the release version of the docker image.
TESTED:
Removed the image from the local machine, commented out the new lines (and removed `build`), and then ran the services successfully.
=> Added a minor docker compose comment for skipping the build

pipelines/controller/config/flink-conf.yaml, pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
This is related to #777 but specifically is about the memory bug by which the memory usage of the controller gradually increases after each pipeline run; see [this comment](https://github.com/google/fhir-data-pipes/issues/777#issuecomment-1703142297).
TESTED:
Ran the pipeline several times using the controller and verified that the 5 GB memory increase that used to happen each run is not happening anymore. There is still some increase in the memory after each run but much lower (so the memory leak issue is not completely fixed).
No? …
=> Added a GC hint at the end of each pipeline run

docker/config/flink-conf.yaml
Reverts google/fhir-data-pipes#801
=> Revert "Temporarily reducing the Flink memory params for low resource machines"

pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
Fixes #839
Registering the micrometer gauges as strong references, so that they are not cleared immediately after GC.
Tested the pipeline batch and verified that the pipeline metrics are shown correctly in the UI.
=> Register micrometer gauges as strong references

Dockerfile, bunsen/pom.xml, docker-entrypoint.sh, docker/config/application.yaml, pipelines/batch/Dockerfile, pipelines/batch/README.md, pipelines/batch/pom.xml, pipelines/common/pom.xml, pipelines/controller/README.md, pipelines/controller/config/application.yaml, pipelines/controller/pom.xml, pipelines/pom.xml, pipelines/streaming/Dockerfile, pipelines/streaming/README.md, pipelines/streaming/pom.xml, pom.xml, utils/resource-monitor/monitor_pipeline.sh
Issue: #853
This addressed all of the "critical" vulnerabilities (22) discovered by GCP Artifact Registry and 28 of the "high" ones. For a comparison, see [this snapshot version](https://pantheon.corp.google.com/artifacts/docker/cloud-build-fhir/us/fhir-analytics/main/sha256:d4e599b056e7f5a7b1ba5376eac8b4bc5564bc4e87c9f66ca56c0780bd5fcbbf;tab=vulnerabilities?project=cloud-build-fhir) and [this released version](https://pantheon.corp.google.com/artifacts/docker/cloud-build-fhir/us/fhir-analytics/main/sha256:8f8219a1276a6baee98894a8d499759892ed95a659ca349e4ba7374187b23b97;tab=vulnerabilities?project=cloud-build-fhir). Note many of the reports are duplicate of each other.
This also does some version clean-up to have consistency between the code and the released docker versions.
TESTED:
Ran …
=> Addressed "critical" docker image vulnerabilities

Dockerfile, bunsen/pom.xml, docker-entrypoint.sh, docker/config/flink-conf.yaml, pipelines/batch/Dockerfile, pipelines/batch/README.md, pipelines/batch/pom.xml, pipelines/common/pom.xml, pipelines/controller/README.md, pipelines/controller/config/application.yaml, pipelines/controller/pom.xml, pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java, pipelines/pom.xml, pipelines/streaming/Dockerfile, pipelines/streaming/README.md, pipelines/streaming/pom.xml, pom.xml, utils/resource-monitor/monitor_pipeline.sh
Fixes #865 
(Please note only the second commit belongs to this PR.)
TESTED:
Ran a locally built controller image and verified that resource tables are not created for DWH dirs with errors.
=> Prevent creation of resource tables for erroneous DWH dirs

pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewApplicator.java, pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewDefinition.java, pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewDefinitionException.java, pipelines/common/src/test/java/com/google/fhir/analytics/ParquetUtilTest.java, pipelines/common/src/test/java/com/google/fhir/analytics/view/ViewApplicatorTest.java, pipelines/common/src/test/java/com/google/fhir/analytics/view/ViewDefinitionTest.java, pipelines/common/src/test/resources/observation_many_constants_view.json, pipelines/common/src/test/resources/observation_no_subject.json, pipelines/common/src/test/resources/observation_patient_id_view.json, pipelines/common/src/test/resources/patient_addresses_view.json, pipelines/pom.xml
This is the second step for implementing #821 and is a follow-up to #880. This adds support for `constant` and `where` constructs of `ViewDefinition`s.
TESTED:
Added unit-tests covering many scenarios (line coverage: `ViewApplicator` 83%, `ViewDefinition` 68%).
=> adds where and constant support for views

bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java, bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/R4AvroConverterTest.java, bunsen/bunsen-avro/src/test/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitorTest.java, bunsen/bunsen-core-r4/src/test/java/com/cerner/bunsen/r4/TestData.java, bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/StructureDefinitions.java
Fixes #912 
The error was that `uuid` was properly added in [`TYPE_TO_CONVERT` map](https://github.com/google/fhir-data-pipes/blob/467485553b1d88a4aa319b53f32d2d4d42c2e3e1/bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java#L102) but missing from list of [`PRIMITIVE_TYPES`](https://github.com/google/fhir-data-pipes/blob/467485553b1d88a4aa319b53f32d2d4d42c2e3e1/bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/StructureDefinitions.java#L24). This PR also adds a unit-test to prevent similar discrepancies in the future.
TESTED:
Relied on the added unit tests and e2e tests.
No? Please take some time and review [Java](https://google.github.io/styleguide/javaguide.html) and [Python](https://google.github.io/styleguide/pyguide.html) style …
=> adds uuid to the list of primitive types

pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcFetchHapi.java
Resolves https://github.com/google/fhir-data-pipes/issues/925
TESTED:
=> Fixes the changes in handling of text vs zipped resources in recent HAPI versions

bunsen/pom.xml, pipelines/pom.xml
This fixes the build failure issues of #934 and #862 so that we can upgrade our HAPI dep version.
TESTED:
Relied on e2e/unit tests.
=> Fixed jackson version issues for hapi upgrade

pom.xml
This is to fix [this vulnerability](https://github.com/google/fhir-data-pipes/security/dependabot/17).
TESTED:
Relied on e2e/unit tests.
=> pin spotless version to fix vulnerability

docker/.env
Makes a minor modification in default memory to work for 48 cores machines by default; also updates the comment (I think the previous number was not correct).
TESTED:
Ran the controller locally; otherwise relying on the e2e test.
=> Minor change/fix in default memory

README.md
Now that we have enabled codecov again, we should update the old badge too.
TESTED:
Verified the links.
=> updated codecov badge

pipelines/common/pom.xml, pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewApplicator.java, pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewDefinition.java, pipelines/common/src/test/java/com/google/fhir/analytics/view/SQLonFHIRv2Test.java, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/README.md, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/basic.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/collection.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/combinations.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/constant.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fhirpath.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fhirpath_numbers.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_boundary.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_empty.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_extension.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_first.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_join.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_oftype.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_reference_keys.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/foreach.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/logic.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/union.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/validate.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/view_resource.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/where.json
Fixes #954, barring some issues that need to be fixed/discussed in upstream repos (marked as `TODO`s).
As a side effect we get a nice increase on the test coverage of the `view` package.
TESTED:
This is all about tests!
=> Added SQL-on-FHIR v2 repo tests

pipelines/common/src/test/java/com/google/fhir/analytics/view/SQLonFHIRv2Test.java, pipelines/common/src/test/resources/sql-on-fhir-v2-test-result.json
This is a follow-up to #1033.
TESTED:
Ran the [sql-on-fhir-v2 test_report app](https://github.com/FHIR/sql-on-fhir-v2/tree/master/test_report) locally and tested the output.
=> Fixes SoFv2 test result format

pipelines/batch/src/main/java/com/google/fhir/analytics/ConvertResourceFn.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FetchPatientHistory.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FetchPatients.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FetchResources.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FetchSearchPageFn.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FhirEtl.java, pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcResourceWriter.java, pipelines/batch/src/main/java/com/google/fhir/analytics/ProcessGenericRecords.java, pipelines/batch/src/main/java/com/google/fhir/analytics/ReadJsonFilesFn.java, pipelines/common/src/main/java/com/google/fhir/analytics/ParquetUtil.java
Fixes #1024 using the `@FinishBundle` idea mentioned [here](https://github.com/google/fhir-data-pipes/issues/1024#issuecomment-2080379243). I ended up not fixing #288 (i.e., separation of `ParquetIO`) for reasons that I will describe there when I close that issue soon.
TESTED:
Ran the pipeline on Dataflow and made sure Parquet files are created.
=> Fixes Dafaflow Parquet issue by using finishBundle

pipelines/common/src/test/resources/sql-on-fhir-v2-tests/basic.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/collection.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/combinations.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/constant.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fhirpath.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fhirpath_numbers.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_boundary.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_empty.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_extension.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_first.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_join.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_oftype.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/fn_reference_keys.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/foreach.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/logic.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/union.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/validate.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/view_resource.json, pipelines/common/src/test/resources/sql-on-fhir-v2-tests/where.json
The `fhirVersion` numbers have been updated in the SoFv2 repo; bringing those changes here.
TESTED:
Ran the tests and checked they pass.
=> Updated tests from SoFv2 repo

pipelines/batch/pom.xml, pipelines/batch/src/main/java/com/google/fhir/analytics/ParquetMerger.java, pipelines/common/pom.xml, pipelines/common/src/main/java/com/google/fhir/analytics/DwhFiles.java, pipelines/controller/src/main/java/com/google/fhir/analytics/DwhFilesManager.java, pipelines/pom.xml
Fixes #1011 
It also updates some deps/versions.
TESTED:
Did a sample run with a S3 bucket for the output and verified the output files are created (note this needed `AWS_REGION`, `AWS_SECRET_ACCESS_KEY` and `AWS_ACCESS_KEY_ID` to be set):
```shell
java -cp ./pipelines/batch/target/batch-bundled.jar com.google.fhir.analytics.FhirEtl --sourceJsonFilePattern=[PATH]/synthea-hiv/768_patients/* --resourceList="Patient" --parallelism=30 --outputParquetPath=s3://[BUCKET]/parquet_from-json_768_flink --runner=FlinkRunner
```
No? Unsure? -> …
=> Added S3 dep and some version updates

query/Dockerfile, query/requirements.txt, query/test_duckdb.ipynb
Fixes #987 
TESTED:
Built the docker image locally, i.e., from the` query/` dir:
```shell
docker build -t my-fhir-views .
```
then ran and tested the created image:
```shell
docker run -p 10002:8888 --network cloudbuild -v "[PATH]/docker/dwh:/dwh" --name fhir-views my-fhir-views
```
=> Added test_duckdb.ipynb

docker/config/views/condition_flat_view.json, docker/config/views/diagnostic_report_flat_view.json, docker/config/views/encounter_flat_view.json, docker/config/views/immunization_flat_view.json, docker/config/views/location_flat_view.json, docker/config/views/medication_request_flat_view.json, docker/config/views/observation_flat_view.json, docker/config/views/organization_flat_view.json, docker/config/views/patient_flat_view.json, docker/config/views/practitioner_flat_view.json, docker/config/views/practitioner_role_flat_view.json, docker/config/views/procedure_flat_view.json, pipelines/common/src/test/resources/encounter_flat_view.json
This is just to make it clear what version of FHIR are the intended target of the sample ViewDefinition resources. They may work for other versions too but we have not tested it, so better to be specific.
I discovered this issue when running the validator of the FHIR-IG publisher tool on these views (which was defaulting to R5).
TESTED:
Ran the pipeline locally and checked some of the produced views.
=> Added fhirVersion to ViewDefinitions

doc/docs/concepts/concepts.md, doc/docs/tutorials/add_dashboard.md
Fixed some broken links (there are probably more).
TESTED:
Ran the docs site locally and tested the links.
=> Fixed some doc links

pipelines/batch/src/main/java/com/google/fhir/analytics/BulkExportUtil.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FetchSearchPageFn.java, pipelines/batch/src/main/java/com/google/fhir/analytics/HapiRowDescriptor.java, pipelines/batch/src/main/java/com/google/fhir/analytics/metrics/FlinkJobListener.java, pipelines/batch/src/main/java/com/google/fhir/analytics/metrics/PipelineMetricsProvider.java, pipelines/batch/src/test/java/com/google/fhir/analytics/ReadJsonFromFileTest.java, pipelines/common/src/main/java/com/google/fhir/analytics/DwhFiles.java, pipelines/common/src/main/java/com/google/fhir/analytics/FetchUtil.java, pipelines/common/src/main/java/com/google/fhir/analytics/FhirStoreUtil.java, pipelines/common/src/main/java/com/google/fhir/analytics/GcpStoreUtil.java, pipelines/common/src/main/java/com/google/fhir/analytics/JdbcConnectionPools.java, pipelines/common/src/main/java/com/google/fhir/analytics/ParquetUtil.java, pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewManager.java, pipelines/controller/src/main/java/com/google/fhir/analytics/metrics/Stats.java
After merging #1248 it seems that continuous-build runs are much slower. It is odd as the first successful run of #1248 was fine  (back in November), but the recent runs were slow. This is an attempt to address a potential related issue introduced in `FetchSearchPageFn.java`.
This PR also updates some of license line dates as the original PR was created in 2024 but merged in 2025.
TESTED:
No? Unsure? -> execute command `git pull --rebase …
=> Fixed a delay issue of a recent commit and license updates

docker/config/views/condition_flat_view.json, docker/config/views/diagnostic_report_flat_view.json, docker/config/views/encounter_flat_view.json, docker/config/views/immunization_flat_view.json, docker/config/views/medication_request_flat_view.json, docker/config/views/observation_flat_view.json, docker/config/views/organization_flat_view.json, docker/config/views/practitioner_flat_view.json, docker/config/views/practitioner_role_flat_view.json, docker/config/views/procedure_flat_view.json
Mostly adding the display fields for concept codes which is required for Text-to-SQL efforts (follow-up PRs).
TESTED:
I ran the pipeline with these updated views and generated materialized Parquet views.
=> Updated flat views

pipelines/batch/src/main/java/com/google/fhir/analytics/FetchSearchPageFn.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FhirEtl.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FhirEtlOptions.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FhirSearchUtil.java, pipelines/common/src/main/java/com/google/fhir/analytics/FetchUtil.java, pipelines/common/src/test/java/com/google/fhir/analytics/FetchUtilTest.java, pipelines/controller/config/application.yaml, pipelines/controller/src/main/java/com/google/fhir/analytics/DataProperties.java, pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java, pipelines/controller/src/test/java/com/google/fhir/analytics/ControlPanelApplicationTests.java, pipelines/controller/src/test/java/com/google/fhir/analytics/DataPropertiesTest.java, pipelines/controller/src/test/java/com/google/fhir/analytics/metrics/PipelineMetricsProviderTest.java, pipelines/controller/src/test/resources/data/patient-count-sample.json
This is done because the `/metadata` check may skip the auth flow on the FHIR server.
TESTED:
Ran the controller locally and verified that it works.
=> Added Patient check for the auth case

bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/HapiCompositeConverter.java
This is related to #1431 and in particular [this comment](https://github.com/google/fhir-data-pipes/issues/1431#issuecomment-3211454198). Note that [extension.url](https://hl7.org/fhir/extensibility.html#extension) should not be null but we are changing the code regardless to be more defensive.
TESTED:
Relying on unit/e2e tests.
=> Preventing a potential NPE

docker/compose-controller-spark-sql-released.yaml, docker/compose-controller-spark-sql-single.yaml, docker/compose-controller-spark-sql.yaml, e2e-tests/controller-spark/Dockerfile
Resolves #1485 
TESTED:
[Java](https://google.github.io/styleguide/javaguide.html) and
[Python](https://google.github.io/styleguide/pyguide.html) style guides.
No? Unsure? ->
[configure your IDE](https://github.com/google/google-java-format).
before creating this pull request and added all formatting changes to my
commit.
No? Unsure? -> execute command `git pull --rebase upstream …
=> Migrate Bitnami Spark Docker image version

bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/converters/DefinitionToAvroVisitor.java, bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/tools/GenerateAggregatedSchemas.java, bunsen/bunsen-avro/src/main/java/com/cerner/bunsen/avro/tools/GenerateSchemas.java, bunsen/bunsen-core/src/main/java/com/cerner/bunsen/definitions/DefinitionVisitorsUtil.java, pipelines/batch/src/main/java/com/google/fhir/analytics/ConvertResourceFn.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FhirEtl.java, pipelines/batch/src/main/java/com/google/fhir/analytics/FhirSearchUtil.java, pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcFetchHapi.java, pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcFetchOpenMrs.java, pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcResourceWriter.java, pipelines/batch/src/main/java/com/google/fhir/analytics/ReadJsonFn.java, pipelines/common/src/main/java/com/google/fhir/analytics/FetchUtil.java, pipelines/controller/src/main/java/com/google/fhir/analytics/DwhFilesManager.java, pipelines/controller/src/main/java/com/google/fhir/analytics/PipelineManager.java
- String.split to Guava Splitter
Resolves https://github.com/google/fhir-data-pipes/issues/1479
TESTED:
[Java](https://google.github.io/styleguide/javaguide.html) and
[Python](https://google.github.io/styleguide/pyguide.html) style guides.
No? Unsure? ->
[configure your IDE](https://github.com/google/google-java-format).
before creating this pull request and added all formatting changes …
=> Fixes StringSplitter Error Prone bug pattern

pipelines/batch/src/main/java/com/google/fhir/analytics/BulkExportApiClient.java, pipelines/batch/src/main/java/com/google/fhir/analytics/ConvertResourceFn.java, pipelines/batch/src/main/java/com/google/fhir/analytics/JdbcFetchHapi.java, pipelines/common/pom.xml, pipelines/common/src/main/java/com/google/fhir/analytics/DwhFiles.java, pipelines/common/src/main/java/com/google/fhir/analytics/FetchUtil.java, pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewDefinition.java, pipelines/common/src/main/java/com/google/fhir/analytics/view/ViewSchema.java, pipelines/controller/src/main/java/com/google/fhir/analytics/DwhFilesManager.java, pipelines/controller/src/main/java/com/google/fhir/analytics/metrics/TextFormat.java
Resolves https://github.com/google/fhir-data-pipes/issues/1475
TESTED:
[Java](https://google.github.io/styleguide/javaguide.html) and
[Python](https://google.github.io/styleguide/pyguide.html) style guides.
No? Unsure? ->
[configure your IDE](https://github.com/google/google-java-format).
before creating this pull request and added all formatting changes to my
commit.
No? Unsure? -> …
=> Fixes StatementSwitchToExpressionSwitch Error Prone bug pattern
